Add relevant papers
NullHypothesis/censorbib pull request #16
Opened 2023-05-03 11:36 UTC by anadahz

2023-05-06 17:02 UTC, NullHypothesis commented
Hey Vasilis, I hope you've been well! Thanks for this PR. My unwritten policy has been to only add work that has been peer-reviewed by well-known CS venues. It's not a perfect policy but it strikes me as better than the alternative of erring on the side of completion: There are lots of technical reports out there and I cannot keep up with adding them all, let alone keeping track of revisions. That said, Ververis2021a does seem like a great addition. Would you mind rebasing onto master and formatting the bibtex record like all the others?

2023-05-06 17:03 UTC, NullHypothesis requested changes
See this comment: https://github.com/NullHypothesis/censorbib/pull/16#issuecomment-1537182376

2023-05-09 13:48 UTC, NullHypothesis requested changes
Made several fixes.

2023-05-09 13:48 UTC, NullHypothesis commented on references.bib
> +       title        = {Understanding Internet Censorship in Europe: The Case of Spain},
```suggestion
       title        = {Understanding {Internet} Censorship in {Europe}: The Case of {Spain}},
```

2023-05-09 13:48 UTC, NullHypothesis commented on references.bib
> +       publisher    = {Association for Computing Machinery},
```suggestion
       publisher    = {ACM},
```

2023-05-09 13:48 UTC, NullHypothesis commented on references.bib
> +       booktitle    = {13th ACM Web Science Conference 2021},
```suggestion
       booktitle    = {Web Science Conference},
```

2023-05-09 13:48 UTC, NullHypothesis commented on references.bib
> +       url          = {https://doi.org/10.1145/3447535.3462638},
```suggestion
       url          = {https://dl.acm.org/doi/pdf/10.1145/3447535.3462638},
```

2023-05-09 14:31 UTC, anadahz commented
> Made several fixes.

Thank you!

2023-05-09 14:44 UTC, NullHypothesis approved these changes
Looks good, thanks for your help! ❤️

2023-05-09 14:44 UTC, merged