Add five FOCI'24 papers and correct the year of a publication
NullHypothesis/censorbib pull request #25
Opened 2024-02-16 19:46 UTC by gfw-report

This pull request adds three papers and two extended abstracts from FOCI'24. It also corrects the year of a publication.

* Homepage: https://foci.community/foci24.html
* Publications: https://www.petsymposium.org/foci/2024/
* Discussion group: https://github.com/net4people/bbs/issues/329

2024-02-17 18:14 UTC, gaukas commented on references.bib
> +@inproceedings{2024a,
```suggestion
@inproceedings{Tsai2024a,
```

Maybe a typo?

2024-02-24 19:44 UTC, NullHypothesis requested changes
Left a few suggestions. As always, thanks a lot for your help! :heart:

2024-02-24 19:44 UTC, NullHypothesis commented on references.bib
> +	title = {{Internet} Sanctions on {Russian} Media: Implementation and Effects},
That's a typo, no?
```suggestion
	title = {{Internet} Sanctions on {Russian} Media: Actions and Effects},
```

2024-02-24 19:44 UTC, NullHypothesis commented on references.bib
> +	author = {John Kristoff and Max Resing and Moritz M\"{u}eller and Arturo Filast\`{o} and Chris Kanich and Niels ten Oever},
AIUI, the author order is based on rows, not columns.
```suggestion
	author = {John Kristoff and Moritz M\"{u}eller and Arturo Filast\`{o} and Max Resing and Chris Kanich and Niels ten Oever},
```

2024-02-24 19:44 UTC, NullHypothesis commented on references.bib
> +	title = {Just add {WATER}: WebAssembly-based Circumvention Transports},
```suggestion
	title = {Just add {WATER}: {WebAssembly}-based Circumvention Transports},
```

2024-02-24 19:44 UTC, NullHypothesis commented on references.bib
> +	url = {https://www.petsymposium.org/foci/2024/foci-2024-0005.php},
```suggestion
	url = {https://www.petsymposium.org/foci/2024/foci-2024-0005.pdf},
```

2024-02-24 19:44 UTC, NullHypothesis commented on references.bib
> +	title = {Extended Abstract: {Oscur0}: One-shot Circumvention without registration},
```suggestion
	title = {Extended Abstract: {Oscur0}: One-shot Circumvention without Registration},
```

2024-02-24 21:11 UTC, gfw-report commented
Thank you so much for your careful review, @NullHypothesis ! I have fixed them all now. Most of the changes were needed because I based it on an unfinalized version of the publication list: https://github.com/net4people/bbs/issues/329. I will make sure to use the camera-ready version in the future.

2024-02-24 21:29 UTC, NullHypothesis commented on header.tpl
> +            <a href="https://github.com/NullHypothesis/censorbib/commits/master">Last update: 2024-02-25</a>
You leaked a few bits of your geolocation because it's still 2024-02-24 where I live 😉

2024-02-24 21:29 UTC, NullHypothesis approved these changes
Looks good, thanks again!

2024-02-24 21:29 UTC, merged