Add ten FOCI'24 issue 2 papers and Support accent characters in cite names.
NullHypothesis/censorbib pull request #51
Opened 2024-07-17 07:35 UTC by gfw-report

This pull request contains two major components:

1. [Add ten FOCI'24 issue 2 papers.](https://github.com/NullHypothesis/censorbib/commit/0e2fa455c209d7dafe9e5f4af00b0c37e6c1d244)

* PETS publication page: https://www.petsymposium.org/foci/2024/
* FOCI program: https://foci.community/foci24.html#2024-summer-program
* Net4People post: https://github.com/net4people/bbs/issues/376

I do not include the three papers in Session III: Privacy Enhancing Technologies, as they are out of scope of Internet censorship.

---

2. [Support accent characters in cite names.](https://github.com/NullHypothesis/censorbib/commit/beb8b8aacad906b46aefeffa4a28a0797cbc5ed3)

A new commit introduces a cite name that contains an accent character:

> @inproceedings{Müller2024a,

It will cause the bibtex parser to fail with the following two errors:

> failed to extract cite name of: @inproceedings{Müller2024a,

and

> parse failed at 55:17: syntax error: unexpected $end, expecting tCOMM

We have both errors fixed in this commit. The second error is an upstream limitation, which I will try to get it merged to the upstream: https://github.com/nickng/bibtex.

2024-07-17 08:17 UTC, gfw-report commented
> The second error is an upstream limitation, which I will try to get it merged to the upstream: https://github.com/nickng/bibtex.

I opened the pull request: https://github.com/nickng/bibtex/pull/25

2024-07-20 14:23 UTC, NullHypothesis requested changes
One minor comment but looks good! Thanks for your work!

2024-07-20 14:23 UTC, NullHypothesis commented on references.bib
> +	title = {{Extended Abstract}: The Impact of Online Censorship on {LLMs}},
I don't think we need to wrap these in brackets.
```suggestion
	title = {Extended Abstract: The Impact of Online Censorship on {LLMs}},
```

2024-07-20 14:23 UTC, NullHypothesis commented on references.bib
> +	title = {{Extended Abstract}: Leveraging Large Language Models to Identify {Internet} Censorship through Network Data},
```suggestion
	title = {Extended Abstract: Leveraging Large Language Models to Identify {Internet} Censorship through Network Data},
```

2024-07-20 14:23 UTC, NullHypothesis commented on src/main.go
> +var re = regexp.MustCompile(`@[a-z]*\{([\"\p{L}\p{M}\-]*[0-9]{4}[a-z]),`)
Nice fix! :+1:

2024-07-20 15:47 UTC, gfw-report commented
I have now removed `{}` from Extended Abstract. 

Thank you so much for your review, @NullHypothesis !

2024-07-20 17:06 UTC, gfw-report commented
I added two PETS'24 papers in this PR.

2024-07-20 23:11 UTC, NullHypothesis approved these changes
Noice noice, looks great!

2024-07-20 23:11 UTC, merged