feat: add OONI's dnspriv21 paper on DoT/DoH blocking
NullHypothesis/censorbib pull request #9
Opened 2022-06-27 09:15 UTC by bassosimone

2022-06-28 02:55 UTC, NullHypothesis requested changes

2022-06-28 02:55 UTC, NullHypothesis commented on references.bib
> +  booktitle = {{NDSS DNS Privacy Workshop}},
```suggestion
  booktitle = {DNS Privacy Workshop},
```

2022-06-28 02:55 UTC, NullHypothesis commented on references.bib
> +  year = {2021},
Would you mind adding a `publisher = {The Internet Society},`?

2022-07-06 10:47 UTC, bassosimone commented
I think I have implemented the required changes! @NullHypothesis, please take another look! Thank you!

2022-07-07 14:50 UTC, merged